### ISSUE TITLE
The .lib is not generated

### ISSUE THREAD

**Issue by PicosePablo** [fredakilla/brtshaderc#2]
Hi,
Why if I insert this in the BGFX project, the project brtshaderc is generated, but the brtshaderc.lib doesn't exist?
I cannot link to brtshadercRelease (for example) because it does not exist

**Comment by PicosePablo** [comment]
Directly, if I add a stupid line like this in the brtshader project, in vertexdecl.cpp file:
asdjfhaasdfaehreu
and then I compile it, visual studio 2017 told me that all is up to date or if I rebuild, all correct

**Comment by fredakilla** [comment]
I see the problem. The script is not correct on windows.
It miss a configuration() part for visual studio, without it the file brtshaderc.cpp is excluded from the build.
It seems that it also miss some stuff because I have some link errors with an example.
Usually I use it on linux with cmake, I didn't see this error. I think it need a correct rewrite of the script. I'll fix it soon.

**Comment by fredakilla** [comment]
fixed.
Added example too.
